In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('car.data')
df.head(5)

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [3]:
col_name = ['buying','maint','doors','person','lug_boost','safety','class']
df.columns = col_name
df

     buying  maint  doors person lug_boost safety  class
0     vhigh  vhigh      2      2     small    med  unacc
1     vhigh  vhigh      2      2     small   high  unacc
2     vhigh  vhigh      2      2       med    low  unacc
3     vhigh  vhigh      2      2       med    med  unacc
4     vhigh  vhigh      2      2       med   high  unacc
...     ...    ...    ...    ...       ...    ...    ...
1722    low    low  5more   more       med    med   good
1723    low    low  5more   more       med   high  vgood
1724    low    low  5more   more       big    low  unacc
1725    low    low  5more   more       big    med   good
1726    low    low  5more   more       big   high  vgood

[1727 rows x 7 columns]

In [4]:

df.describe()

       buying maint doors person lug_boost safety  class
count    1727  1727  1727   1727      1727   1727   1727
unique      4     4     4      3         3      3      4
top      high  high     3      4       med    med  unacc
freq      432   432   432    576       576    576   1209

In [5]:
for c in col_name:
    print(df[c].value_counts())
    print('-----'*15)

buying
high     432
med      432
low      432
vhigh    431
Name: count, dtype: int64
---------------------------------------------------------------------------
maint
high     432
med      432
low      432
vhigh    431
Name: count, dtype: int64
---------------------------------------------------------------------------
doors
3        432
4        432
5more    432
2        431
Name: count, dtype: int64
---------------------------------------------------------------------------
person
4       576
more    576
2       575
Name: count, dtype: int64
---------------------------------------------------------------------------
lug_boost
med      576
big      576
small    575
Name: count, dtype: int64
---------------------------------------------------------------------------
safety
med     576
high    576
low     575
Name: count, dtype: int64
---------------------------------------------------------------------------
class
unacc    1209
acc       384
good       69
vgood      65
Name: count, dtype: int64
---------------------------------------------------------------------------

In [6]:
df[df.duplicated()]
#to get df with all duplicate values

Empty DataFrame
Columns: [buying, maint, doors, person, lug_boost, safety, class]
Index: []

In [7]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

for c in col_name:
    df[c] = oe.fit_transform(df[[c]])

df

      buying  maint  doors  person  lug_boost  safety  class
0        3.0    3.0    0.0     0.0        2.0     2.0    2.0
1        3.0    3.0    0.0     0.0        2.0     0.0    2.0
2        3.0    3.0    0.0     0.0        1.0     1.0    2.0
3        3.0    3.0    0.0     0.0        1.0     2.0    2.0
4        3.0    3.0    0.0     0.0        1.0     0.0    2.0
...      ...    ...    ...     ...        ...     ...    ...
1722     1.0    1.0    3.0     2.0        1.0     2.0    1.0
1723     1.0    1.0    3.0     2.0        1.0     0.0    3.0
1724     1.0    1.0    3.0     2.0        0.0     1.0    2.0
1725     1.0    1.0    3.0     2.0        0.0     2.0    1.0
1726     1.0    1.0    3.0     2.0        0.0     0.0    3.0

[1727 rows x 7 columns]

In [8]:
#to make input and out format use iloc

X = df.iloc[: , 0:-1]
y = df.iloc[ : , -1]
# here row , coumn splitting

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=1)
rf.fit(X_train, y_train)      
y_pred = rf.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score , precision_score,roc_auc_score,roc_curve

accuracy = accuracy_score(y_test,y_pred)
print(f'accuracy for random forest model:{accuracy}')

accuracy for random forest model:0.953757225433526

In [11]:
# to know fearure importnace
imp = rf.feature_importances_

feature_imp = pd.DataFrame({'Feature': X_train.columns, 'Importance': imp})

print(feature_imp.sort_values(by='Importance',ascending=False))

     Feature  Importance
5     safety    0.283361
3     person    0.228640
0     buying    0.187818
1      maint    0.162427
4  lug_boost    0.079279
2      doors    0.058476

In [12]:
import pickle
pickle.dump(rf, open("car_model.pkl", "wb"))
# for file creation in binary write mode

In [13]:
import streamlit as st
model = pickle.load(open("car_model.pkl","rb"))
st.title("Car Evaluation Prediction")

buying = st.selectbox("Buying Price", ["low","med","high","vhigh"])
maint = st.selectbox("Maintenance", ["low","med","high","vhigh"])
doors = st.selectbox("Doors", [2,3,4,5])
persons = st.selectbox("Persons Capacity", [2,4,"more"])
lug_boot = st.selectbox("Luggage Boot", ["small","med","big"])
safety = st.selectbox("Safety", ["low","med","high"])

if st.button("Predict"):
    input_data = np.array([[buying,maint,doors,persons,lug_boot,safety]])
    prediction = model.predict(input_data)
    st.success(f"Car Acceptability: {prediction[0]}")

2026-04-01 17:55:33.607 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.494
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\G AMRITH VARSHAN\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-04-01 17:55:34.496 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.497 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.498 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.500 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.501 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.502 Session state does not function when running a script without `streamlit run`
2026-04-01 17:55:34.504 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.505 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.506 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.507 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.509 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.510 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.511 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.511 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.512 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.513 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.514 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.515 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.517 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.518 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.520 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.520 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.521 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.521 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.523 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.523 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.524 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.524 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.527 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.527 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.529 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.532 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.535 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.535 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.541 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.542 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.544 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.544 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.545 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.547 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.549 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-01 17:55:34.550 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.